### PR TITLE
[Report Automation] Projection Bugs

### LINKED ISSUE #675: [Report Automation] X and Y-axes are off in Facility Projections
**Describe the bug**
The x-axis in some projection charts is unevenly spaced and the y-axis values are much higher than necessary. 

**To Reproduce**
Generate an automated report for any given state.

**Expected behavior**
The x axis should be evenly spaced and the highest y-value should be closer to the highest y-value in the projection itself.

**Additional context**

### PR DESCRIPTION
**Pull request by neeharmb**
## Projection Bugs

- Change the y-axis maxExtent to the maxValue in a projection--this matches the behavior in the web app. I'm not entirely sure what the rationale was behind adding 100 to the maxValue, but all the projections I've tested look good to me.
- Switch the color of the infectious and hospitalized lines--this also matches the behavior in the web app
- Change x-axis tick values to be calculated based on the current day so they are more evenly spaced per the mocks

Testing:
image

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #675 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/page-weekly-snapshot/FacilityProjectionChart.tsx [hunk 1]
```diff
@@ -91,8 +108,9 @@ const FacilityProjectionChart: React.FC<ProjectionProps> = ({
     axes: [
       {
         orient: "bottom",
-        ticks: 5,
-        tickFormat: (value: Date) => formatDate(new Date(value), "MM/dd"),
+        ticks: numXTicks,
```
Comment (macfarlandian) [inline src/page-weekly-snapshot/FacilityProjectionChart.tsx:111]: I don't think this option does anything anymore in the presence of `tickValues` so you can just remove it
