### PR TITLE
check cases input relative to total input in FacilityInformation form

### LINKED ISSUE #314: Users can enter cases without population, resulting in negative charts
**Describe the bug**
Entering cases for the incarcerated population that exceeds the total population results in peculiar chart behavior. See attached screenshot.

**To Reproduce**

1. Go to 'Add Facilities'
2. Click on Ages Unknown, Current Cases
3. Enter 200
4. See chart

**Expected behavior**
Should highlight red the case numbers box in red if it exceeds the total population number (for both staff and pop).

**Screenshots**
image

### PR DESCRIPTION
**Pull request by glen0071**
## Description of the change

In FacilityInformation component, when inputting integers into Facility Details > Current cases or Total Population, add red highlight to cases if cases exceeds total for any row.

cases-to-total

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #314

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/impact-dashboard/FacilityInformation.tsx [hunk 1]
```diff
@@ -172,6 +172,24 @@ interface AgeGroupRowProps {
...
 const AgeGroupRow: React.FC<AgeGroupRowProps> = (props) => {
   const { model, updateModel } = props;
+  const [inputRelativityError, setInputRelativityError] = useState(false);
+
+  function checkInputRelativity(
+    cases: number | undefined,
+    total: number | undefined,
+  ) {
+    if (cases == undefined) {
+      return setInputRelativityError(false);
```
Comment (jessex) [inline src/impact-dashboard/FacilityInformation.tsx:182]: Are these return statements just being used to terminate at the right location? I have not seen that convention before, personally! I'd probably opt to just have this by one cohesive conditional block:
```
if (cases == undefined) {
  setInputRelativityError(false);
} else if (cases != undefined && total === undefined) {
  setInputRelativityError(true);
} else if (total != undefined && cases > total) {
  setInputRelativityError(true);
} else {
  setInputRelativityError(false);
}
```

File: src/impact-dashboard/FacilityInformation.tsx [hunk 2]
```diff
@@ -172,6 +172,24 @@ interface AgeGroupRowProps {
 
 const AgeGroupRow: React.FC<AgeGroupRowProps> = (props) => {
   const { model, updateModel } = props;
+  const [inputRelativityError, setInputRelativityError] = useState(false);
+
+  function checkInputRelativity(
+    cases: number | undefined,
+    total: number | undefined,
+  ) {
+    if (cases == undefined) {
```
Comment (jessex) [inline src/impact-dashboard/FacilityInformation.tsx:181]: Should this be `===`?

File: src/impact-dashboard/FacilityInformation.tsx [hunk 3]
```diff
@@ -172,6 +172,24 @@ interface AgeGroupRowProps {
...
+      return setInputRelativityError(false);
+    }
+
+    if (cases != undefined && total === undefined) {
```
Comment (jessex) [inline src/impact-dashboard/FacilityInformation.tsx:185]: Should this be `!==` instead of `!=`? Same goes for the next conditional below.

File: src/impact-dashboard/FacilityInformation.tsx (hunk 1 above)
Comment (glen0071) [reply src/impact-dashboard/FacilityInformation.tsx:182]: As a general rule, I'll defer to others on JavaScript. So I'll fix this up this afternoon.

Comment (macfarlandian) [reply src/impact-dashboard/FacilityInformation.tsx:182]: FWIW, this is definitely a convention, nothing wrong with it, just a matter of style. arguably having a big conditional block is a more readable signal that we are checking a series of mutually exclusive conditions but six of one IMO

File: src/impact-dashboard/FacilityInformation.tsx [hunk 4]
```diff
@@ -172,6 +172,22 @@ interface AgeGroupRowProps {
...
+    if (cases === undefined) {
+      setInputRelativityError(false);
+    } else if (cases !== undefined && total === undefined) {
+      setInputRelativityError(true);
+    } else if (total !== undefined && cases > total) {
+      setInputRelativityError(true);
+    } else {
+      setInputRelativityError(false);
+    }
+  }
```
Comment (glen0071) [inline src/impact-dashboard/FacilityInformation.tsx:190]: @jessex this is ready for another look.
