### PR TITLE
Facility Name Updates Not Persisting When Edited from the Multi-Facil…

### LINKED ISSUE #278: Facility Name Updates Not Persisting When Edited from the Multi-Facility Dashboard
**Describe the bug**

A small regression was introduced in #251 where the app errors out when renaming a Facility from the Multi-dashboard page.

**To Reproduce**

1. Go to the multi-dashboard page.
2. Click on a Facility's name to rename it
3. Rename the facility and hit <enter>
4. The facility's name will appear to be updated, but if you refresh the page you'll notice the changes didn't actually persist.  Also, if you open Chrome's dev tools, you'll notice an error.

**Expected behavior**

The Facility's name is actually persisted.

### PR DESCRIPTION
**Pull request by sprad**
…ity Dashboard

## Description of the change

Fixing a minor regression where the facility name was not being updated from the Multi-Facility dashboard.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #278 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/database/index.tsx [hunk 1]
```diff
@@ -397,16 +397,25 @@ export const saveFacility = async (
...
-      const incomingObservedAt = facility.modelInputs.observedAt;
-      const currentFacilityData = await facilityDoc.get();
-      const currentFacility = buildFacility(scenarioId, currentFacilityData);
-      if (
-        incomingObservedAt &&
-        currentFacility.modelInputs.observedAt &&
-        startOfDay(incomingObservedAt) >=
-          startOfDay(currentFacility.modelInputs.observedAt)
-      ) {
+
```
Comment (sprad) [inline src/database/index.tsx:400]: Minor regression I found when testing Multi-scenario stuff.  Not crazy about all of these nested conditionals, but wanted to get this in before today's production deployment

**Comment by SoumyaMahadevan** [comment]
Thanks for fixing!

**Comment by sprad** [comment]
Tested the following cases:

1.  Updating name from a facility row ✅ 
2.  Updating cases from the new Add cases modal ✅ 
3.  Updating a facility from the facility details page (name and case counts) ✅
