### PR TITLE
Don't create facilities from reference data with empty model inputs

### LINKED ISSUE #651: [Shadow data] New facilities added from reference data have incorrect modelInputs
When adding a facility from the modal that lists existing reference facilities for a particular state and system type, the resulting Facility objects have a modelInputs and most recent modelVersions object that has the locale data but case and population counts that are "undefined". These objects should be discarded by the facility merge process and the most recent day with actual (reference) data should be used in their place. There is a bug either in the facility creation process or the facility merge function that is preventing this from being done properly.

### PR DESCRIPTION
**Pull request by macfarlandian**
## Description of the change

This fixes some broken tests against `FacilitiesContext` and also resolves the issue where a facility's `modelInputs` could be blank after creating it from reference data via the `SyncNoUserFacilities` modal.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #651 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by daschi** [comment]
nice! this is similar to what I was about to do for #641. After this merges I'll rebase from here.

File: src/facilities-context/transforms.tsx [hunk 1]
```diff
@@ -106,7 +106,7 @@ function mergeModelVersions({
   userVersions,
   referenceFacility,
 }: Optional<MergedHistoryInputs, "referenceFacility">): ModelInputs[] {
-  const combinedVersions: ModelInputs[] = [...userVersions];
+  const combinedVersions: ModelInputs[] = [...userVersions.filter(hasCases)];
```
Comment (daschi) [inline src/facilities-context/transforms.tsx:109]: I was also considering saving the reference facility's transformed covidCases data directly to the newly mapped userFacility (from `SyncNoUserFacilities` line 258. That way we wouldn't have to filter out the "fake" modelInputs and the userFacility created from the referenceFacility would already have the correct modelInputs and versions. Do you think that would make sense?

Comment (macfarlandian) [reply src/facilities-context/transforms.tsx:109]: hm yeah, I thought about doing that ... I am not dead-set against it necessarily but there were a couple of issues I saw that made this seem like an easier fix, at least within the scope of the bug I was looking at: 

1. by default it sets the current day as `observedAt`, which is likely to be wrong. it should be set to whatever the most recent observed at date is in reference data. not sure how much work that would be to fix
2. i was a little leery of putting data into the user's facilities collection that they didn't actually enter themselves. In practice it's probably not a huge deal but it did seem slightly unclean somehow. We could do it if it's really necessary for some reason, but as far as I could tell for this issue anyway, it's not?

what do you think? is there something I'm missing or something relevant to your ticket that you think might indicate a different fix here?

Comment (daschi) [reply src/facilities-context/transforms.tsx:109]: I need to do some more testing but my initial hunch was that the rtData calculation fetches were firing first with the incorrect modelInputs, and they were being saved as errors after the second round of rtData calculations were requested and returned. I think this fix makes sense for this issue, I can keep digging on the rtData calculations for the referenceFacilities from this modal tomorrow morning.

Comment (macfarlandian) [reply src/facilities-context/transforms.tsx:109]: sounds plausible ... FWIW i didn't really see difference in that behavior with this change

**Comment by macfarlandian** [comment]
@daschi ........ dare I suggest you approve this PR, if you are OK with it? or is that conditional on you digging into your bug a bit more?
