### PR TITLE
Remove Icon Coupling from the InputNameWithIcon Component

### LINKED ISSUE #350: Remove Icon Coupling from the InputNameWithIcon Component
**Describe the bug**
Our current `InputNameWithIcon` [bakes in a toggle](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/design-system/InputNameWithIcon.tsx#L61) to display a folder icon when the passed in `showIcon` property is set to true.  This creates an issue for the new scenario library because the intention of this icon is to be used as a trigger for presenting the Scenario Library modal.  It doesn't make sense to put the Scenario Modal loading code in this otherwise generic component.

**To Reproduce**

N/A - mostly a code refactoring

**Expected behavior**

Rename the `InputNameWithIcon` to `InputName` and remove its functionality to show or hide the folder icon.  This will make the component itself more generic and will also give it parity with its sister `InputDescription` component.  After that refactor, separately include the folder icon in the Scenario Sidebar and add a click handler to it that triggers the display of the Scenario Library Modal.

**Screenshots**

The folder icon highlighted in red below should no longer be tied to the `InputNameWithIcon` and should instead exist independently such that it can trigger the Scenario Library modal when clicked:

Screen Shot 2020-05-08 at 3 04 01 PM

### PR DESCRIPTION
**Pull request by sprad**
## Description of the change

* Removing the Folder Icon coupling from the InputName in order to provide more UI flexibility in where and how we place this folder icon.  This is particularly relevant for the Scenario Library which needs to be triggered by the folder icon.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #350

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by sprad** [comment]
I'm not wild about this implementation, but it works and doesn't seem any better or worse than what we already had in place.

Screen Shot 2020-05-08 at 7 03 42 PM

File: src/design-system/InputName.tsx [hunk 1]
```diff
@@ -46,19 +41,18 @@ interface Props
...
   persistChanges,
   setName,
-  showIcon,
+  border,
   ...passThruProps
 }) => {
   return (
-    <NameLabelDiv>
-      {showIcon && <IconFolder alt="folder" src={iconFolderSrc} />}
+    <NameLabelDiv border={border}>
```
Comment (sprad) [inline src/design-system/InputName.tsx:55]: We no longer embed this Folder Icon within this otherwise generic component.  However we do pass in a new property `border` to optionally display a bottom border if the UI calls for it (i.e. in the `FacilityInputForm` in this case).

File: src/page-multi-facility/ScenarioSidebar.tsx [hunk 2]
```diff
@@ -112,21 +117,30 @@ const ScenarioSidebar: React.FC<Props> = (props) => {
...
-          <ScenarioLibraryModal
-            trigger={<IconFolder alt="folder" src={iconFolderSrc} />}
+        <ScenarioName>
+          {showScenarioLibrary && (
+            <ScenarioLibraryModal
+              trigger={
+                <IconFolder
+                  style={{
+                    marginTop: "8px",
+                  }}
```
Comment (sprad) [inline src/page-multi-facility/ScenarioSidebar.tsx:127]: A side effect of embedding these trigger components within the modal component itself is that we have to do any custom styling inline.  I think that's ok.
