### PR TITLE
Persist Changes to Name and Description in the Scenario Sidebar

### LINKED ISSUE #220: Persist Changes to Name and Description in the Scenario Sidebar
**Describe the bug**

The changes to the name and description in the Scenario Sidebar are no longer being saved to Firestore.

**To Reproduce**

1. Open the app
2. Edit the name and description
3. Refresh the page
4. Notice that the changes are not saved

**Expected behavior**

Editing the name and description in the scenario sidebar persists the changes

**Screenshots**

N/A

**Desktop (please complete the following information):**

- All platforms

**Smartphone (please complete the following information):**

- All platforms

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by sprad**
## Description of the change

Bug fix for issue #220 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #220

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/page-multi-facility/ScenarioSidebar.tsx [hunk 1]
```diff
@@ -63,11 +63,13 @@ const ScenarioSidebar: React.FC<Props> = (props) => {
           name={name}
           setName={setName}
           placeholderValue={scenario?.name}
```
Comment (sprad) [inline src/page-multi-facility/ScenarioSidebar.tsx:65]: I needed to optionally pass a persistence method in because depending on the context we're in we may or may not actually want to save the inputs immediately.  For example, when changes are made in the Sidebar for the Scenario, we won't those changes saved.  When changes are made on the Facility Details page (where these components are also used), we don't want those changes persisted until the user clicks the Save button.

I've tested and verified that both of these use cases now function properly.
